name: Install Ansible on Ubuntu Server

on:
  workflow_dispatch:
  push:

jobs:
  install-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show HOME path
        run: echo "HOME is: $HOME"

      - name: Test SSH setup
        shell: bash
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "test" > ~/.ssh/testfile
          ls -la ~/.ssh

      - name: Set up SSH key
        run: |
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> /home/runner/.ssh/known_hosts


      - name: Install Ansible remotely
        shell: bash
        run: |
          ssh -tt ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install -y ansible
            ansible --version
          EOF
